- hosts: localhost
  become: true
  sudo: yes
  
  vars:
    jenkins_repo_url: "deb http://pkg.jenkins.io/debian-stable binary/"
    jenkins_repo_key_url: "https://pkg.jenkins.io/debian/jenkins-ci.org.key"
	
  tasks:	 
- name: Add Jenkins apt repository key.
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present
	 
- name: Add Jenkins apt repository.
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes
	
- name: updates a server
  apt: update_cache=yes
  
- name: Install jenkins
  apt:
    name: jenkins
    state: present