--- # loop playbook example
- hosts: localhost
  become_use: timor
  become: yes
  connection: ssh
  gather_facts: no
  tasks:
     - name: ADD a list of users
       user: name={{ item }} state=present
       with_items:
          - user1
          - user2
          - user3
