--- # loop playbook example
- hosts: localhost
  user: timor
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
      palybook_version: 0.1b
  vars_prompt:
     - name: pkgtoinsatll
       prompt: insatll with package?
       default: telnet
       private: no
  
  tasks:
     - name: insatll any package
       apt: pkg={{ pkgtoinsatll }} state=latest
